// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvZp8DjYi4xwZjbgBof9hTEVZCf-P8a0Y',
    appId: '1:1007230724660:web:1b5467ee13604c065ab861',
    messagingSenderId: '1007230724660',
    projectId: 'prabhdeep-bus-project',
    authDomain: 'prabhdeep-bus-project.firebaseapp.com',
    databaseURL: 'https://prabhdeep-bus-project-default-rtdb.firebaseio.com',
    storageBucket: 'prabhdeep-bus-project.appspot.com',
    measurementId: 'G-945CLHL7JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrku9XN-lyINY8JXHuNQBKcIICmfuFHo',
    appId: '1:1007230724660:android:d63767e0cd0e151f5ab861',
    messagingSenderId: '1007230724660',
    projectId: 'prabhdeep-bus-project',
    databaseURL: 'https://prabhdeep-bus-project-default-rtdb.firebaseio.com',
    storageBucket: 'prabhdeep-bus-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqWDekGeOE2SML4-ZP_kVkO1Uzm_q5dU',
    appId: '1:1007230724660:ios:0e0c050db24b63985ab861',
    messagingSenderId: '1007230724660',
    projectId: 'prabhdeep-bus-project',
    databaseURL: 'https://prabhdeep-bus-project-default-rtdb.firebaseio.com',
    storageBucket: 'prabhdeep-bus-project.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxqWDekGeOE2SML4-ZP_kVkO1Uzm_q5dU',
    appId: '1:1007230724660:ios:4d8971ba24b4029f5ab861',
    messagingSenderId: '1007230724660',
    projectId: 'prabhdeep-bus-project',
    databaseURL: 'https://prabhdeep-bus-project-default-rtdb.firebaseio.com',
    storageBucket: 'prabhdeep-bus-project.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
